"""Initial migration

Revision ID: d5526dedf344
Revises: 
Create Date: 2025-12-17 21:27:17.885456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5526dedf344'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create policy_profiles first without foreign key to tenants (circular dependency)
    op.create_table('policy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=True),
    sa.Column('weights_json', sa.JSON(), nullable=True),
    sa.Column('ruleset_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_profiles_id'), 'policy_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_policy_profiles_name'), 'policy_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_policy_profiles_tenant_id'), 'policy_profiles', ['tenant_id'], unique=False)
    # Create tenants with foreign key to policy_profiles
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('policy_profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_profile_id'], ['policy_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Now add the foreign key from policy_profiles to tenants
    op.create_foreign_key('policy_profiles_tenant_id_fkey', 'policy_profiles', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_tenants_api_key_hash'), 'tenants', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_label'), 'tenants', ['label'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('risk_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_external_id'), 'accounts', ['external_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hash'), 'api_keys', ['hash'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('identity_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_key_hash', sa.String(length=255), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_entities_entity_key_hash'), 'identity_entities', ['entity_key_hash'], unique=False)
    op.create_index(op.f('ix_identity_entities_entity_type'), 'identity_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_identity_entities_id'), 'identity_entities', ['id'], unique=False)
    op.create_index(op.f('ix_identity_entities_tenant_id'), 'identity_entities', ['tenant_id'], unique=False)
    op.create_table('ledger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_hash', sa.String(length=255), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_events_correlation_id'), 'ledger_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_created_at'), 'ledger_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_events_event_hash'), 'ledger_events', ['event_hash'], unique=True)
    op.create_index(op.f('ix_ledger_events_event_type'), 'ledger_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ledger_events_id'), 'ledger_events', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_events_previous_event_hash'), 'ledger_events', ['previous_event_hash'], unique=False)
    op.create_index(op.f('ix_ledger_events_tenant_id'), 'ledger_events', ['tenant_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('device_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('device_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_hash', sa.String(length=255), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_fingerprints_account_id'), 'device_fingerprints', ['account_id'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_device_hash'), 'device_fingerprints', ['device_hash'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_id'), 'device_fingerprints', ['id'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_ip_hash'), 'device_fingerprints', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_tenant_id'), 'device_fingerprints', ['tenant_id'], unique=False)
    op.create_table('identity_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['identity_entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['identity_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_relationships_from_entity_id'), 'identity_relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_identity_relationships_id'), 'identity_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_identity_relationships_tenant_id'), 'identity_relationships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_identity_relationships_to_entity_id'), 'identity_relationships', ['to_entity_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('content_ref', sa.Text(), nullable=True),
    sa.Column('fingerprints_json', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('pvid', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assurance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_account_id'), 'uploads', ['account_id'], unique=False)
    op.create_index(op.f('ix_uploads_decision'), 'uploads', ['decision'], unique=False)
    op.create_index(op.f('ix_uploads_external_id'), 'uploads', ['external_id'], unique=False)
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.create_index(op.f('ix_uploads_ingestion_id'), 'uploads', ['ingestion_id'], unique=True)
    op.create_index(op.f('ix_uploads_pvid'), 'uploads', ['pvid'], unique=False)
    op.create_index(op.f('ix_uploads_received_at'), 'uploads', ['received_at'], unique=False)
    op.create_index(op.f('ix_uploads_tenant_id'), 'uploads', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_id'), 'webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('decision_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('inputs_hash', sa.String(length=255), nullable=False),
    sa.Column('outputs_hash', sa.String(length=255), nullable=False),
    sa.Column('ledger_hash', sa.String(length=255), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_certificates_certificate_id'), 'decision_certificates', ['certificate_id'], unique=True)
    op.create_index(op.f('ix_decision_certificates_id'), 'decision_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_decision_certificates_issued_at'), 'decision_certificates', ['issued_at'], unique=False)
    op.create_index(op.f('ix_decision_certificates_ledger_hash'), 'decision_certificates', ['ledger_hash'], unique=False)
    op.create_index(op.f('ix_decision_certificates_tenant_id'), 'decision_certificates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_decision_certificates_upload_id'), 'decision_certificates', ['upload_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_id'), 'risk_signals', ['id'], unique=False)
    op.create_index(op.f('ix_risk_signals_signal_type'), 'risk_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_risk_signals_tenant_id'), 'risk_signals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_upload_id'), 'risk_signals', ['upload_id'], unique=False)
    op.create_table('evidence_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=True),
    sa.Column('storage_refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['decision_certificates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_packs_certificate_id'), 'evidence_packs', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_evidence_packs_id'), 'evidence_packs', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_packs_status'), 'evidence_packs', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_packs_tenant_id'), 'evidence_packs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_packs_tenant_id'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_status'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_id'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_certificate_id'), table_name='evidence_packs')
    op.drop_table('evidence_packs')
    op.drop_index(op.f('ix_risk_signals_upload_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_tenant_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_signal_type'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_decision_certificates_upload_id'), table_name='decision_certificates')
    op.drop_index(op.f('ix_decision_certificates_tenant_id'), table_name='decision_certificates')
    op.drop_index(op.f('ix_decision_certificates_ledger_hash'), table_name='decision_certificates')
    op.drop_index(op.f('ix_decision_certificates_issued_at'), table_name='decision_certificates')
    op.drop_index(op.f('ix_decision_certificates_id'), table_name='decision_certificates')
    op.drop_index(op.f('ix_decision_certificates_certificate_id'), table_name='decision_certificates')
    op.drop_table('decision_certificates')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_uploads_tenant_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_received_at'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_pvid'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_ingestion_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_external_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_decision'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_account_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_identity_relationships_to_entity_id'), table_name='identity_relationships')
    op.drop_index(op.f('ix_identity_relationships_tenant_id'), table_name='identity_relationships')
    op.drop_index(op.f('ix_identity_relationships_id'), table_name='identity_relationships')
    op.drop_index(op.f('ix_identity_relationships_from_entity_id'), table_name='identity_relationships')
    op.drop_table('identity_relationships')
    op.drop_index(op.f('ix_device_fingerprints_tenant_id'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_ip_hash'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_id'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_device_hash'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_account_id'), table_name='device_fingerprints')
    op.drop_table('device_fingerprints')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_ledger_events_tenant_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_previous_event_hash'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_event_type'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_event_hash'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_created_at'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_correlation_id'), table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_index(op.f('ix_identity_entities_tenant_id'), table_name='identity_entities')
    op.drop_index(op.f('ix_identity_entities_id'), table_name='identity_entities')
    op.drop_index(op.f('ix_identity_entities_entity_type'), table_name='identity_entities')
    op.drop_index(op.f('ix_identity_entities_entity_key_hash'), table_name='identity_entities')
    op.drop_table('identity_entities')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_external_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_tenants_label'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_api_key_hash'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_policy_profiles_tenant_id'), table_name='policy_profiles')
    op.drop_index(op.f('ix_policy_profiles_name'), table_name='policy_profiles')
    op.drop_index(op.f('ix_policy_profiles_id'), table_name='policy_profiles')
    op.drop_table('policy_profiles')
    # ### end Alembic commands ###

